### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependencies

### ISSUE THREAD

**Issue by NobelLiu** [PromiseKit/Alamofire-#1]
```
Box:wxs Nobel$ pod install

[!] Invalid `Podfile` file: syntax error, unexpected '~', expecting keyword_end
    pod "PromiseKit/Alamofire" ~> 4.0
                                ^.


 #  from /Users/Nobel/Develop/wxshell_ios/wxs/Podfile:7
 #  -------------------------------------------
 #      pod "PromiseKit", "~> 3.4"
 >      pod "PromiseKit/Alamofire" ~> 4.0
 #      pod 'Alamofire'
 #  -------------------------------------------
Box:wxs Nobel$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `PromiseKit/Alamofire (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PromiseKit/Alamofire (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

My podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "wxs" do
    pod "PromiseKit", "~> 3.4"
    pod "PromiseKit/Alamofire", "~> 4.0"
    pod 'Alamofire'
    pod 'Zip'
end

**Comment by S0MMS** [comment]
Is there any resolution to this?  I'm getting this same error as well.

**Comment by nathanhosselton** [comment]
Looks like the Alamofire subspec is currently commented out of our podspec. I imagine this was an oversight. Probably can have this fixed up tonight.

Thank you @NobelLiu for reporting and @S0MMS for the reminder.

**Comment by nathanhosselton** [comment]
Oh, duh, this is actually because Alamofire 4.0 is not yet released so its spec doesn't exist in the pod trunk. This is also why we had our Alamofire subspec commented out in our podspec. There's nothing we can do about this on our end as podspecs won't allow outside dependencies. Maybe there's a workaround. I'll look into it.

More than likely Alamofire 4.0 will be released soon anyway though.

**Comment by mxcl** [comment]
This is fixed. And indeed, we couldn't release this subspec until Alamofire released theirs.
