### ISSUE TITLE
Possible to reduce Deployment target to 8.0?

### ISSUE THREAD

**Issue by bphenriques** [PromiseKit/Alamofire-#11]
Good evening,

I would like to add this repo through pod "PromiseKit/Alamofire" onto a project with a deployment target of 8.0, however the project's minimum deployment target is 9.0 (https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L39). I had to copy the files to my project. Is there any reasoning for not having the deployment target same as the PromiseKit? If not, would it be possible to reduce the deployment target 8.0 (https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L24)?

Thank you,
Bruno

**Comment by mxcl** [comment]
I'm guessing there was a reason, but we should test it and see what happens. I do not have time to test it right now, perhaps you can?

**Comment by mxcl** [comment]
Looks like we can.

Though notably, I had to rebuild Alamofire from Carthage as its deployment target was 9.0 with my old checkout, so presumably Alamofire 4.x was previously 9.0 also.

Will submit.

**Comment by bphenriques** [comment]
Hey, sorry I only caught up with your answers now.

I am using your source actively on a project and so, far there has been no issues from with any apple device with 8.0.

Thank you for taking a look into the issue
