### ISSUE TITLE
Carthage: Wrong Alamofire version in doc

### ISSUE THREAD

**Issue by DarkSatyr** [PromiseKit/Alamofire-#12]
On doc page Carthage section shows 

```
github "PromiseKit/Alamofire" ~> 1.0
```

But when I'm trying to run Carthage I'm getting errors:

```
carthage update --platform ios
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching PromiseKit
*** Checking out Alamofire at "4.2.0"
*** Checking out Alamofire at "1.0.5"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.5) failed with exit code 1:
error: pathspec '1.0.5' did not match any file(s) known to git.
```

My `Cartfile` is:

```
github "mxcl/PromiseKit" ~> 4.0
github "Alamofire/Alamofire" ~> 4.0
github "PromiseKit/Alamofire" ~> 1.0
```

It looks like it tries to fetch Alamofire at "1.0.5" and fails, any ideas?

**Comment by mxcl** [comment]
1.0.5 exists: https://github.com/PromiseKit/Alamofire-/releases/tag/1.0.5

So, seems like a bug in Carthage.

**Comment by mxcl** [comment]
OK,  if you do `github "PromiseKit/Alamofire-" ~> 1.0` it works.

Seemingly still a bug in Carthage since you can clone it without the -, but that's the fix.

**Comment by mxcl** [comment]
README updated.

**Comment by DarkSatyr** [comment]
thanks, now it works!
