### ISSUE TITLE
Issue when dependency uses PromiseKit / AwaitKit

### ISSUE THREAD

**Issue by nobre84** [PromiseKit/Alamofire-#14]
Hi, the extension are very useful, thanks!
I'm having an issue when integrating in the following scenario:
- I develop a private spec "B" that depends on PromiseKit 4.0 and AwaitKit 2.0
- I have an app target "A" that depended on pod "B" and PromiseKit 4.0
Now I need PromiseKit/Alamofire 4.0 in the app
After swapping PromisetKit with PromiseKit/Alamofire in the target I get the following build error in AwaitKit framework
My target deployment is iOS 9.0, do you have any idea what this might be ? Anything me or AwaitKit need to do ?

![screen shot 2017-02-23 at 07 50 01](https://cloud.githubusercontent.com/assets/459535/23256086/bd1dc7a2-f99c-11e6-848e-821af5c890f6.png)

**Comment by mxcl** [comment]
Somewhere deep in Xcode’s settings, your deployment target is not 9.

**Comment by mxcl** [comment]
Check that your Podfile’s deployment target is 9.

**Comment by nobre84** [comment]
The app requires 9.0. My private Podspec only requires 8.0, as well as PromiseKit, AwaitKit and Alamofire.
Its weird that this only happens when the app integrates the pods

**Comment by mxcl** [comment]
Sorry, but you weren't clear which deployment target the `Podfile` specifies; for example the top of one of mine reads:

```ruby
platform :ios, '9.0'
swift_version = '3.0'
use_frameworks!
```

**Comment by nobre84** [comment]
Yes, the Podfile also complies with the 9.0 requirement with `platform :ios, '9.0'`

**Comment by nobre84** [comment]
I noticed that if I manually open the Pods project and change the deployment target on AwaitKit and Alamofire to 9.0, the app can build successfully.

**Comment by mxcl** [comment]
Actually this is odd because PromiseKit only requires 8. No spec requires 9: https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec

**Comment by ghost** [comment]
I'm running into the same issue here. Hope to see a fix soon as being able to use this library on 8.0 would really make my life easier.

**Comment by mxcl** [comment]
This particular subspec is a single file, so simply only require PromiseKit and then drag and drop this single file into your project.

I have no clue about a fix, as said, nothing in PromiseKit requires iOS 9. Either CocoaPods is at fault or there is something more mysterious going on.

**Comment by mxcl** [comment]
Closing, reopen if still the case, but I've just been over all this with a fine tooth comb and there is nothing I can see that PromiseKit is doing wrong.
