### ISSUE TITLE
Uploading multipart form data

### ISSUE THREAD

**Issue by sssilver** [PromiseKit/Alamofire-#18]
Hello,

It looks like the extension doesn't cover the method for uploading multipart form data: http://cocoadocs.org/docsets/Alamofire/4.4.0/Functions.html#/MultipartFormData

Am I missing something?

Thanks.

**Comment by mxcl** [comment]
Our extension is not complete, PR welcome. If you check our source, you can see there isn't much to it. So you can easily write as an extension in your app and then submit it back for inclusion in this project.

Sorry it's not there.

**Comment by mxcl** [comment]
Closing due to lack of movement.
