### ISSUE TITLE
README example: withMethod -> method

### ISSUE THREAD

**Issue by neoneye** [PromiseKit/Alamofire-#19]
I'm unable to get the [readme example code](https://github.com/PromiseKit/Alamofire-/blob/master/README.markdown) to compile with Xcode 8.3.2.

The current code is this. Not compiling

    Alamofire.request("https://httpbin.org/get", withMethod: .GET)

Proposed solution: Compiles.

    Alamofire.request("https://httpbin.org/get", method: .get)

**Comment by mxcl** [comment]
PR welcome.
