### ISSUE TITLE
xcodebuild timeout

### ISSUE THREAD

**Issue by tib** [PromiseKit/Alamofire-#2]
Carthage build is not working for me.
Xcode Version 8.0 beta 6 (8S201h)
carthage version 0.17.2

Cartfile:

```
github "PromiseKit/Alamofire" ~> 1.0
```

carthage update

``` bash
carthage update
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching PromiseKit
*** Checking out Alamofire at "3cc5b4e8453bec9fd6b973d60e6b0605a38e4cf4"
*** Checking out Alamofire at "1.0.0"
*** Checking out PromiseKit at "4.0.0"
*** xcodebuild output can be found in /var/folders/k2/s653z37j24v2n0rrwg5_yhkm0000gn/T/carthage-xcodebuild.Sod3l7.log
xcodebuild timed out while trying to read iOS Example.xcodeproj 😭
```

**Comment by nathanhosselton** [comment]
I think this may have been fixed. Try again.

**Comment by mxcl** [comment]
This Alamofire failing to build.

**Comment by giacaglia** [comment]
Getting the same problem here

**Comment by mxcl** [comment]
K this is a Carthage bug, it checks both `Alamofire` and `PromiseKit/Alamofire` out into the same directory.

**Comment by tib** [comment]
Updated a couple of things, but I have a different issue now:

carthage update
**\* Fetching Alamofire
**\* Fetching Alamofire
**\* Fetching PromiseKit
**\* Checking out Alamofire at "4.0.1"
**\* Checking out Alamofire at "1.0.2"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.2) failed with exit code 1:
error: pathspec '1.0.2' did not match any file(s) known to git.

cartfile

```
github "PromiseKit/Alamofire" ~> 1.0.2
```

Xcode Version 8.0 (8A218a)

carthage version
0.18

**Comment by mxcl** [comment]
It's the same issue.

**Comment by tib** [comment]
thought so. ;)

**Comment by mxcl** [comment]
I'm not sure how to fix this independently of Carthage except by renaming this repo. So I guess I better do that.

**Comment by mxcl** [comment]
`Alamofire-` will do.

**Comment by oddysee** [comment]
Another afflicted user. Going to have to remove this dependency as I can't seem to work around it.

**Comment by mxcl** [comment]
Someone should report the bug to Carthage.

**Comment by oddysee** [comment]
That's a good suggestion. Someone [has](https://github.com/Carthage/Carthage/issues/1522). I've commented as well.

**Comment by mxcl** [comment]
I've renamed the repo. Fingers crossed nothing broke.

Sorry for the delay, renaming was scary to me.

I've not tested this fixes it. But if it doesn't we'll reopen.
