### ISSUE TITLE
Not possible to get request response when catching errors

### ISSUE THREAD

**Issue by lmcd** [PromiseKit/Alamofire-#20]

**Comment by mxcl** [comment]
Yes, Alamofire does not provide the response in the error so the error has no response information.

**Comment by Hornobster** [comment]
Is there a way to get the response object? I would like to execute different code depending on the status code.

**Comment by mxcl** [comment]
You have to write your own promise that captures the response and adds it to your own error objects.

**Comment by mxcl** [comment]
Or if it's just one time then you can do it inline:

```swift
Promise { fulfill, reject in
    Alamofire.request(…) { response, error in
        //…
    }
}
```
