### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by vsg24** [PromiseKit/Alamofire-#22]
What's the point of this lib? We can just use completion handlers that are built into Swift, can't we?

**Comment by mxcl** [comment]
If you don't understand the point in Promises then you will not find this library useful. Thanks.

**Comment by nathanhosselton** [comment]
If you're new to the concept of [Promises](https://en.wikipedia.org/wiki/Futures_and_promises), the initial paragraph and proceeding example at the [PromiseKit base repo](https://github.com/mxcl/PromiseKit), as well as the [introductory guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md), should provide some insight. But to directly answer your question, yes, you can simply use completion handlers, and doing so is already quite nice in Swift. Promises, arguably, make the completion handler pattern [much nicer](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#abstracting-away-asychronicity), however.
