### ISSUE TITLE
Cannot build framework with Alamofire

### ISSUE THREAD

**Issue by QuentinArnault** [PromiseKit/Alamofire-#23]
Hi,

I'm a Cocoapods Rome user and I cannot build my dependencies with the Alamofire subspec.
I've made some investigations.

With the following Podfile:
```ruby
plugin 'cocoapods-rome'
platform :ios, '9.0'

target :Dependencies do
    pod 'PromiseKit/Alamofire', '~> 6.0.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
```

I ran the `pod install` command which has generated a `PromiseKit.framework` without Alamofire subspec headers.

<img width="643" alt="capture d ecran 2018-02-16 a 00 15 39" src="https://user-images.githubusercontent.com/1578026/36286120-921a3172-12ae-11e8-8045-0be2f90e49af.png">

In order to compare, I have tested same Podfile but with another subspec

```ruby
plugin 'cocoapods-rome'
platform :ios, '9.0'

target :Dependencies do
    pod 'PromiseKit/OMGHTTPURLRQ', '~> 6.0.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
```

I this case, generated framework has OMGHTTPURLRQ headers.

<img width="620" alt="capture d ecran 2018-02-16 a 00 14 27" src="https://user-images.githubusercontent.com/1578026/36286154-b2aaf49e-12ae-11e8-940b-d1d3025eed29.png">

Maybe the problem comes from the trailing `-`  in github Alamofire projet name (`Alamofire-`).

Regards,
Quentin

**Comment by mxcl** [comment]
What’s the error message?

**Comment by mxcl** [comment]
Sounds like a Rome issue report it there.

**Comment by QuentinArnault** [comment]
There is not error message, just missing files in generated framework. I'll check with CocoaPoads team.

**Comment by mxcl** [comment]
Yeah, if CocoaPods doesn't generate the dependency then it seems like it must be their bug, we specific the dependency:

https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L45-L53
