### ISSUE TITLE
'fwd.h' file not found in PromiseKit-umbrella.h

### ISSUE THREAD

**Issue by HVNT** [PromiseKit/Alamofire-#28]
**Currently cannot build Project after including Pod PromiseKit/Alamofire.** The error I am getting is 'fwd.h' file not found (which is clearly in the PromiseKit pod directory, as shown below). 
- Swift version 4.1.2
- Xcode version 9.4.1

Errors:
<img width="297" alt="screen shot 2018-07-30 at 10 31 58 am" src="https://user-images.githubusercontent.com/3422089/43403887-41507780-93e4-11e8-8a5c-9cefecc7dca1.png">

PromiseKit Pod Directory:
<img width="235" alt="screen shot 2018-07-30 at 10 32 04 am" src="https://user-images.githubusercontent.com/3422089/43403907-4ca4610a-93e4-11e8-8ce4-f04e5c99b318.png">

Podfile: 
<img width="429" alt="screen shot 2018-07-30 at 10 31 47 am" src="https://user-images.githubusercontent.com/3422089/43403799-062d1370-93e4-11e8-9401-de9cdfb40328.png">

Linked Frameworks and Libraries:
<img width="1130" alt="screen shot 2018-07-30 at 10 34 11 am" src="https://user-images.githubusercontent.com/3422089/43403833-2550bc2a-93e4-11e8-9586-da02eaeeefcd.png">

**Comment by mxcl** [comment]
CocoaPods bug, `pod deintegrate` then `pod install` until it works. Check CocoaPods is up-to-date. Report the bug against them (this has been happening for several years).

**Comment by HVNT** [comment]
Keep doing it "until it works" ? I've done the two commands you recommended a few times already. It's not working. Are you sure this bug is on CocoaPods and not this Pod?

**Comment by HVNT** [comment]
The issue is not with the other Pod's, only this one. If the issue was with CocoaPods wouldn't other Pods be failing as well? The build works if I remove PromiseKit/Alamofire...

**Comment by mxcl** [comment]
There are maybe 20 different reports of this on PromiseKit itself, I suggest searching for those and following the instructions people left there.

**Comment by mxcl** [comment]
> The issue is not with the other Pod's, only this one.

This Pod is much more complicated than normal pods. Some race condition happens inside CocoaPods and has caused this issue for hundreds of people over the years, feel free to see how they fixed it by searching the PromiseKit issue tracker.
