### ISSUE TITLE
Catch issue: PMKFinalizer

### ISSUE THREAD

**Issue by sashberd** [PromiseKit/Alamofire-#32]
Thanks for such great addon for Alamofire.

I tried to rewrite my old Alamofire code to your new framework, but I get an error:

> Cannot convert return expression of type 'PMKFinalizer' to return type Promise\<DataRequest\>

My code is :

 ```
return firstly {
            Alamofire.request(route).validate().responseJSON()
            }.compactMap({ (responseJson, response) in
                guard let json = try? JSONDecoder().decode(T.self, from: response.data!) else {
                    throw AFError.responseSerializationFailed(reason: .jsonSerializationFailed(error: APIHandlerError.errorInDeserialization)
                )}
                guard let reply = json as? BaseResponse else{
                    throw AFError.responseSerializationFailed(reason: .jsonSerializationFailed(error: APIHandlerError.errorInDeserialization)
                )}
                
                return nil
            }).catch{ error in
                let t = 1 ---> Here I get compiler error
                 return nil
            }
```
From your documentation looks like my code is good, maybe there is an update for documentation or I miss something?

**Comment by mxcl** [comment]
`catch` returns `PMKFinalizer`, also you cannot return `nil` inside the `catch` you can only return `Void`.

You didn't specify what your function return type is.

What is your intent? `catch` terminates the promise chain, you cannot return a `Promise`, only `PMKFinalizer`. If you want to return a Promise, you cannot `catch`.

https://github.com/mxcl/PromiseKit/blob/master/Documentation/FAQ.md#where-should-i-put-my-catch

**Comment by sashberd** [comment]
Thanks for you fats response @mxcl 
Here is my function  
`private static func performRequest<T:Decodable>(route: APIRouter, isAnimatedRequest: Bool, onSuccess successCallback: @escaping (T) -> Void, onError errorCallback: @escaping (Any, String) -> Void) -> Promise<DataRequest>`

My aim was to throw error from promise and catch it inside chainable catch as you describe [here](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#failing-chains)

**Comment by mxcl** [comment]
You have to remove the `catch`.

**Comment by mxcl** [comment]
The link above talks about putting the `catch` at the lowest sensible level, here the API is deliberately forcing that.

Do you need the `catch` there?

**Comment by mxcl** [comment]
LMK if you need further help.

**Comment by mxcl** [comment]
If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).
