### ISSUE TITLE
Info.plist missing?

### ISSUE THREAD

**Issue by JetForMe** [PromiseKit/Alamofire-#40]
Hmm. I just did a `carthage update --platform ios` and I can't build PMKAlamofire because `Info.plist` is missing, yet still referenced in the project file. My Cartfile specifies `~> 3.2`.

**Comment by mxcl** [comment]
CI tests that our Carthage package builds and 3.2.4 passed:

https://travis-ci.org/PromiseKit/PMKAlamofire/jobs/516937986

**Comment by JetForMe** [comment]
Weird. I deleted the entire Carthage folder and tried again, and I still get this issue.

**Comment by JetForMe** [comment]
Specifying 3.2.3:

```
ProcessInfoPlistFile /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/PMKAlamofire/bad-tag-3.2.4/Build/Intermediates.noindex/ArchiveIntermediates/PMKAlamofire/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/PMKAlamofire.framework/Info.plist /Users/me/Projects/Clients/Company/repo/iOS/Controller/Carthage/Checkouts/PMKAlamofire/Info.plist (in target: PMKAlamofire)
    cd /Users/me/Projects/Clients/Company/repo/iOS/Controller/Carthage/Checkouts/PMKAlamofire
    builtin-infoPlistUtility /Users/me/Projects/Clients/Company/repo/iOS/Controller/Carthage/Checkouts/PMKAlamofire/Info.plist -expandbuildsettings -format binary -platform iphoneos -o /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/PMKAlamofire/bad-tag-3.2.4/Build/Intermediates.noindex/ArchiveIntermediates/PMKAlamofire/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/PMKAlamofire.framework/Info.plist
error: Build input file cannot be found: '/Users/me/Projects/Clients/Company/repo/iOS/Controller/Carthage/Checkouts/PMKAlamofire/Info.plist'
```

**Comment by JetForMe** [comment]
Yeah, your file is there. Something about checking out with Carthage makes the file not show up.

**Comment by mxcl** [comment]
Well, I'm saying 3.2.4 checked out with Carthage and built in CI.

3.2.3 may well be different. Ensure you get 3.2.4

**Comment by JetForMe** [comment]
I wasn't clear. I tried forcing 3.2.3 in my Cartfile because a few days ago I was able to build just fine. It didn't help. The error is identical for `~> 3.2` (which I assume resolves to 3.2.4) and `~> 3.2.3`. If I check out your code manually using git, I get a project file that contains `Info.plist`. Moreover, the project file I get via Carthage has `Info.plist` under `Sources` in the project file, but the one I check out manually has it at the top level.

**Comment by JetForMe** [comment]
If I specify `== 3.2.3` in my Cartfile, everything builds

**Comment by mxcl** [comment]
Delete the Carthage cache.

**Comment by JetForMe** [comment]
I tried that, but same result. When I cd into the `org.carthage.CarthageKit/dependencies/PMKAlamofire` directory, my bash prompt (which shows the current git branch) shows `(BARE:(bad-tag-3.2.4))`.

**Comment by mxcl** [comment]
So you deleted the whole of `org.carthage.CarthageKit`?

**Comment by JetForMe** [comment]
Yup

**Comment by JetForMe** [comment]
Note that if I use `== 3.2.3`, the dependency shown is `(BARE:(3.2.3))`.

**Comment by mxcl** [comment]
The `bad-tag-3.2.4` tag is because I mucked up the main PromiseKit git submodule, so I have to preserve that. If Carthage is picking it that is strange. I'll change the name

**Comment by mxcl** [comment]
K, done, delete cache and try again?

**Comment by JetForMe** [comment]
That worked, and without deleting the cache. Thank you!

**Comment by mxcl** [comment]
Sorry about this issue!

**Comment by JetForMe** [comment]
No worries, thanks for fixing it so quickly!
