### ISSUE TITLE
Please specify license.

### ISSUE THREAD

**Issue by Yukimune** [PromiseKit/Alamofire-#42]
Hi, we using this library for some project.
But, you're not specify the license, so we wondering if  we can't use it for production.

Is this project licensed under MIT License same as Alamofire?

Thank you !

**Comment by mxcl** [comment]
It's licensed the same as PromiseKit itself, MIT.

**Comment by mxcl** [comment]
I pushed a `LICENSE` file and will tag new versions shortly.
