### ISSUE TITLE
Not compatible with Alamofire 5

### ISSUE THREAD

**Issue by lmcd** [PromiseKit/Alamofire-#44]

**Comment by robertjanetzko** [comment]
as this seems no longer to be maintained, I updated my fork to work with alamofire 5 and swift 5.2: https://github.com/robertjanetzko/PMKAlamofire

**Comment by MiltonPacheco89** [comment]
> as this seems no longer to be maintained, I updated my fork to work with alamofire 5 and swift 5.2: https://github.com/robertjanetzko/PMKAlamofire

Hello Robert, I'm having issues with 'PromiseKit/Alamofire', I'm new to cocoa pods, can you explain to me how to use your fork?, I'm following the steps in your documentation but I'm still getting the error (Alamofire 4 required)

this is how my Podfile looks like:

```
pod 'Alamofire', '~> 5.1'
  pod 'AlamofireImage', '~> 4.1'
  pod 'Moya', '~> 14'
  pod 'PromiseKit', '~> 6'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
  pod 'Moya/RxSwift', '~> 14'
```
Thanks.

**Comment by robertjanetzko** [comment]
according to https://guides.cocoapods.org/using/the-podfile.html (section "From a podspec in the root of a library repo") I think you should use:

`pod 'PromiseKit/Alamofire', :git => 'https://github.com/robertjanetzko/PMKAlamofire.git'`

but I only use carthage, so I didn't test it with cocoapods

**Comment by garyhooper** [comment]
Thanks for doing this!

Any way around the cocoapods error, other than downloading?
```
[!] There are multiple dependencies with different sources for `PromiseKit` in `Podfile`:

- PromiseKit/CorePromise
- PromiseKit/Alamofire (from `https://github.com/robertjanetzko/PMKAlamofire.git`)
```

**Comment by garyhooper** [comment]
Switching to Swift Package Manager for this still presents a conflict:
```
because PMKAlamofire >=3.2.2 depends on Alamofire 4.0.0..<5.0.0 and root depends on Alamofire 5.2.1..<6.0.0, PMKAlamofire >=3.2.2 is forbidden.
And because root depends on PMKAlamofire 3.2.4..<4.0.0, version solving failed.
```

@robertjanetzko your `Package.swift` looks correct. Any suggestions for me?

**Comment by mehmetbaykar** [comment]
Hi everyone!
Any news on conversion to Swift 5.3 with library update?

**Comment by mxcl** [comment]
We could add a new subspec for Alamofire 5.

This is a trivial task that anyone could have done by now. This is pretty low on my task list.

**Comment by mxcl** [comment]
Released 4.0.0

**Comment by garyhooper** [comment]
Latest version is depending on Alamofire 4.9.1, instead of more current 5.x.

**Comment by mxcl** [comment]
lol I suck.

PR welcome. Again.

**Comment by HakanSAYAR** [comment]
Will you update the latest version? @mxcl

**Comment by mxcl** [comment]
I haven't worked with Swift in 3 years so I'm honestly not convinced I am qualified at this point.
