### ISSUE TITLE
Is it possible to retrieve the DataResponse object in `.responseJSON().then`?

### ISSUE THREAD

**Issue by dickfickling** [PromiseKit/Alamofire-#5]
Right now the responseJSON promise extension only returns `response.result.value`. Would it not make more sense to still somehow include the entire DataResponse object?

I'm trying to access `response.response.statusCode`, and it currently seems there's no way to handle that using the PromiseKit Alamofire extension

**Comment by mxcl** [comment]
Yes, agreed. I'll take a look at this.

**Comment by dickfickling** [comment]
Thanks. For now I've updated my extension locally to `fulfill(response)` rather than `fulfill(value)`. Happy to make that or a better fix in a PR if you've got any ideas

**Comment by mxcl** [comment]
It doesn't make sense to provide the raw `Response` type as then consumers in PromiseKit will have to unwrap the `result` into a `.success` even though we already have guaranteed that it succeeded. So if we are to provide more we should bundle a custom type, or provide the other items in a tuple.

The other option is like what we do for `CLLocationManager` etc.

**Comment by NinoScript** [comment]
What about `fulfill((value, response))`?

**Comment by mxcl** [comment]
> What about fulfill((value, response))?

Maybe this is best. Though I dislike the fact the response contains the `result`, it is perhaps better to just pass the whole thing than to be confusing and create a parallel object that has it removed. Undecided. Sorry this is not resolved yet. I haven't had any good ideas.

Like in the mean time it is very simple to wrap the Alamofire requests yourself.

**Comment by NinoScript** [comment]
Sorry, I wasn't explicit enough, I meant the `HTTPURLResponse` one, not the `DataResponse`.

Like this:
```
/// Adds a handler to be called once the request has finished.
public func responseJSON(options: JSONSerialization.ReadingOptions = .allowFragments) -> Promise<(Any, HTTPURLResponse?)> {
    return Promise { fulfill, reject in
        responseJSON(queue: nil, options: options, completionHandler: { response in
            switch response.result {
            case .success(let value):
                fulfill(value, response.response)
            case .failure(let error):
                reject(error)
            }
        })
    }
}
```

And maybe `response.response` can be force unwrapped when `response.result` was a `.success`, I'm not sure.

**Comment by mxcl** [comment]
I added a `PMKDataResponse` that has everything that `Alamofire.DataReponse<Any>` has except `result` and `value`.

In order to maintain source compatibility it is a new method:

```
rq.responseJSON(with: .response).then {
}
```

It is not too late to change this method signature.
