### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by kuyazee** [PromiseKit/Alamofire-#6]
What version uses swift 2.3?

**Comment by mxcl** [comment]
There is no Alamofire pod for Swift 2.3

PromiseKit itself is version 3 for Swift 2.3, as detailed in its README.

**Comment by kuyazee** [comment]
So you don't have a compatible version for swift 2.3 on PromiseKit/Alamofire?

**Comment by mxcl** [comment]
We do not sorry. However there are pods provided by other people that do. Or look at the code. Wrapping your own promises is trivial.
